@startuml
!include uml-wttch.puml

top to bottom direction
skinparam linetype ortho


class AbstractAutowireCapableBeanFactory
class AbstractBeanFactory
interface AliasRegistry << interface >>
interface AutowireCapableBeanFactory << interface >>
interface BeanDefinitionRegistry << interface >>
interface BeanFactory << interface >>
interface ConfigurableBeanFactory << interface >>
interface ConfigurableListableBeanFactory << interface >>
class DefaultListableBeanFactory
class DefaultSingletonBeanRegistry
class FactoryBeanRegistrySupport
interface HierarchicalBeanFactory << interface >>
interface ListableBeanFactory << interface >>
interface Serializable << interface >>
class SimpleAliasRegistry
interface SingletonBeanRegistry << interface >>
'class XmlBeanFactory

AbstractAutowireCapableBeanFactory  $extend     AbstractBeanFactory
AbstractAutowireCapableBeanFactory  $implement  AutowireCapableBeanFactory
AbstractBeanFactory                 -[#008200,dashed]-^  ConfigurableBeanFactory
AbstractBeanFactory                 -[#000082,plain]-^  FactoryBeanRegistrySupport
AutowireCapableBeanFactory          -[#008200,plain]-^  BeanFactory
BeanDefinitionRegistry              -[#008200,plain]-^  AliasRegistry
ConfigurableBeanFactory             -[#008200,plain]-^  HierarchicalBeanFactory
ConfigurableBeanFactory             -[#008200,plain]-^  SingletonBeanRegistry
ConfigurableListableBeanFactory     -[#008200,plain]-^  AutowireCapableBeanFactory
ConfigurableListableBeanFactory     -[#008200,plain]-^  ConfigurableBeanFactory
ConfigurableListableBeanFactory     -[#008200,plain]-^  ListableBeanFactory
DefaultListableBeanFactory          -[#000082,plain]-^  AbstractAutowireCapableBeanFactory
DefaultListableBeanFactory          -[#008200,dashed]-^  BeanDefinitionRegistry
DefaultListableBeanFactory          -[#008200,dashed]-^  ConfigurableListableBeanFactory
DefaultListableBeanFactory          -[#008200,dashed]-^  Serializable
DefaultSingletonBeanRegistry        -[#000082,plain]-^  SimpleAliasRegistry
DefaultSingletonBeanRegistry        -[#008200,dashed]-^  SingletonBeanRegistry
FactoryBeanRegistrySupport          -[#000082,plain]-^  DefaultSingletonBeanRegistry
HierarchicalBeanFactory             -[#008200,plain]-^  BeanFactory
ListableBeanFactory                 -[#008200,plain]-^  BeanFactory
SimpleAliasRegistry                 -[#008200,dashed]-^  AliasRegistry
'XmlBeanFactory                      -[#000082,plain]-^  DefaultListableBeanFactory
@enduml
