@startuml
top to bottom direction
skinparam linetype ortho

!include ../uml-wttch.puml

interface AliasRegistry << interface >> {
    别名注册接口
}
interface SingletonBeanRegistry << interface >> {
    单例注册接口
}

class SimpleAliasRegistry {
    简单别名注册实现类
    使用 ConcurrentHashMap 来存储
}


interface HierarchicalBeanFactory << interface >> {
    层次化、包含父 BeanFactory
}

HierarchicalBeanFactory $iExtend  BeanFactory


interface ListableBeanFactory << interface >> {
    可列举 Bean
    +getBeanDefinitionNames(): String[]
}


interface AutowireCapableBeanFactory << interface >> {
    创建对象、自动装配依赖
    初始化 bean、销毁 bean
}

AutowireCapableBeanFactory $iExtend BeanFactory


interface ConfigurableBeanFactory << interface >> {
    可配置: 配置 bean 工厂的功能
}


class AbstractAutowireCapableBeanFactory
class AbstractBeanFactory
interface BeanDefinitionRegistry << interface >>
interface BeanFactory << interface >>
interface ConfigurableListableBeanFactory << interface >>
class DefaultListableBeanFactory
class DefaultSingletonBeanRegistry
class FactoryBeanRegistrySupport

SimpleAliasRegistry                 $implement  AliasRegistry
AbstractAutowireCapableBeanFactory  -[#000082,plain]-^  AbstractBeanFactory
AbstractAutowireCapableBeanFactory  -[#008200,dashed]-^  AutowireCapableBeanFactory
AbstractBeanFactory                 -[#008200,dashed]-^  ConfigurableBeanFactory
AbstractBeanFactory                 -[#000082,plain]-^  FactoryBeanRegistrySupport
BeanDefinitionRegistry              -[#008200,plain]-^  AliasRegistry
ConfigurableBeanFactory             -[#008200,plain]-^  HierarchicalBeanFactory
ConfigurableBeanFactory             -[#008200,plain]-^  SingletonBeanRegistry
ConfigurableListableBeanFactory     -[#008200,plain]-^  AutowireCapableBeanFactory
ConfigurableListableBeanFactory     -[#008200,plain]-^  ConfigurableBeanFactory
ConfigurableListableBeanFactory     -[#008200,plain]-^  ListableBeanFactory
DefaultListableBeanFactory          -[#000082,plain]-^  AbstractAutowireCapableBeanFactory
DefaultListableBeanFactory          -[#008200,dashed]-^  BeanDefinitionRegistry
DefaultListableBeanFactory          -[#008200,dashed]-^  ConfigurableListableBeanFactory
DefaultSingletonBeanRegistry        -[#000082,plain]-^  SimpleAliasRegistry
DefaultSingletonBeanRegistry        -[#008200,dashed]-^  SingletonBeanRegistry
FactoryBeanRegistrySupport          -[#000082,plain]-^  DefaultSingletonBeanRegistry
ListableBeanFactory                 -[#008200,plain]-^  BeanFactory
@enduml
